terraform-google-modules/terraform-google-cloud-storage

- README.md
- examples/simple_example/README.md
- examples/simple_example/main.tf
- examples/simple_example/outputs.tf
- examples/simple_example/variables.tf
- test/fixtures/simple_example/main.tf
- test/fixtures/simple_example/outputs.tf
- test/integration/simple_example/controls/gcp.rb
- test/integration/simple_example/controls/gsutil.rb
- test/integration/simple_example/inspec.yml
What else is missing for an initial release on the registry?
> Fix simple example and tests

- Makefile
Implements https://github.com/terraform-google-modules/terraform-google-module-template/pull/21
> Wrap the current directory in quotes so that paths with spaces do not cause failures

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- examples/simple_example/main.tf
- examples/simple_example/versions.tf
- outputs.tf
- test/setup/versions.tf
Fixes #13 using the same approach we [used](https://github.com/terraform-google-modules/terraform-google-folders/pull/20) for folders.
> Fix bug in outputs when removing buckets

- Makefile
Fixes:
1. Fixed the typo for docker_test_cleanup in the Makefile
> Update docker_test_cleanup in Makefile

- test/fixtures/multiple_buckets/main.tf
Fixes:
1. Increased length of random bucket name in fixture.
> Increasing random length of bucket name in fixture

- examples/simple_bucket/README.md
- examples/simple_bucket/main.tf
- examples/simple_bucket/variables.tf
- examples/simple_bucket/versions.tf
- main.tf
- modules/simple_bucket/main.tf
- variables.tf
Fix #51 
Also clean up simple bucket example to be clearer.
> convert lifecycle action object to map

- .github/workflows/linter.yaml
- Makefile
- Adds CFT lint workflow to this module
> Enable CFT Lint bot

- .github/workflows/linter.yaml
Disabling for now as discussed offline
> Disable lint bot due to fork issue

- modules/simple_bucket/main.tf
- Fixes simple_bucket lifecycle created_before field lookup
- Adds is_live field to simple_bucket lifecycle
> Improves simple bucket lifecycle

- main.tf
- modules/simple_bucket/main.tf
Fixes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/89
> Fixes deprecation of is_live lifecycle rule

- CHANGELOG.md
> chore: release 1.7.2

- main.tf
> fix: Remove deprecated list() function usage

- examples/simple_bucket/main.tf
- modules/simple_bucket/README.md
> fix: Use correct IAM view role in example

- README.md
- main.tf
- variables.tf
Please consider this PR as a solution to fix #131.
> fix: Correct behavior of website and cors variables.

- README.md
fixes #123 
Looks like release please is not updating readmes
> chore: update readme to new module version

- modules/simple_bucket/main.tf
Add the following lifecycle rule conditions:
* custom_time_before
* days_since_custom_time
* days_since_noncurrent_time
* noncurrent_time_before
Closes: #144
> feat: Add missing lifecycle rules conditions simple_bucket

- modules/simple_bucket/README.md
- modules/simple_bucket/main.tf
- modules/simple_bucket/variables.tf
Fixes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/149
Signed-off-by: Danny Rehelis <autogun@gmail.com>
> simple_bucket module to support website configuration

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
Bumps devtools to pickup new CFT cli release used in CFT codelab
> chore: bump devtools

- README.md
- main.tf
- modules/simple_bucket/README.md
- modules/simple_bucket/main.tf
- modules/simple_bucket/variables.tf
- modules/simple_bucket/versions.tf
- variables.tf
- versions.tf
> feat!: add support for public_access_prevention

- README.md
- examples/simple_bucket/main.tf
- main.tf
- metadata.yaml
- modules/simple_bucket/README.md
- modules/simple_bucket/main.tf
- modules/simple_bucket/metadata.yaml
- modules/simple_bucket/variables.tf
- modules/simple_bucket/versions.tf
- variables.tf
- versions.tf
This PR provides the autoclass feature for both  multiple_buckets and simple_bucket.
Closes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/220
> feat(TPG >= 4.46)!: adds support to autoclass

- metadata.display.yaml
- modules/simple_bucket/metadata.display.yaml
Generate `medadata.display.yaml` file.
> chore: Generate metadata.display.yaml

- modules/simple_bucket/metadata.yaml
This PR updates the connection metadata for simple_bucket module.
> chore: add connection metadata for GCE instance_template
