terraform-google-modules/terraform-google-cloud-storage

- README.md
- examples/simple_example/README.md
- examples/simple_example/main.tf
- examples/simple_example/variables.tf
- main.tf
- test/fixtures/simple_example/main.tf
- test/integration/simple_example/controls/gsutil.rb
- variables.tf
Fixes https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/4
> Enable `bucket_policy_only` by default, allowing overrides on a per-bucket level

- .gitignore
- CONTRIBUTING.md
- Makefile
- build/int.cloudbuild.yaml
- test/setup/.gitignore
- test/setup/README.md
- test/setup/iam.tf
- test/setup/main.tf
- test/setup/make_source.sh
- test/setup/outputs.tf
- test/setup/variables.tf
- test/setup/versions.tf
It seems like this module is using outdated testing container & Makefile for CI, so here's an update.
Was able to successfully run tests locally. Took these from the terraform-google-network module.
> Update Makefile & test setup for CI

- main.tf
If we create numerous buckets with a single instance of this module they will all have the same labels as it stands today.
When exporting cost metrics to bigquery we may want to distinguish the cost per bucket.
When performing cost queries, labels are the way to group resources today (unfortunately we cannot query on bucket name), adding the unique name as a label is a good way to perform a query on a single bucket with regards to its' cost. Until Big Query cost analysis let's us query on the bucket name, this is a workaround.
Thoughts?
> Include name of bucket as label for cost analysis

- main.tf
I want to create a bucket by verified domain name.
I do it through terraform:
```
Error: googleapi: Error 400: Invalid argument, invalid
on .terraform/modules/cloud_storage/terraform-google-modules-terraform-google-cloud-storage-c011106/main.tf line 21, in resource "google_storage_bucket" "buckets":
21: resource "google_storage_bucket" "buckets" {
```
I do it through web UI:
All because of the line, it forbids me to create baskets with domain names through terraforms.
https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/main.tf#L27
Because label value have only hyphens (-), underscores (_), lowercase characters, and numbers are allowed. International characters are allowed.
> Replace dot on a dash in label value

- README.md
- main.tf
- variables.tf
Resolves #27 
This PR allows for users to specify the `default_kms_key_name` attribute to enable encryption.
Encryption can be enabled on a bucket by bucket basis similar to the existing settings: `versioning` and `force_delete`
The TF handles for empty strings because while an empty string is a valid input that results in a normal google managed key bucket, terraform will see this as a change every `terraform apply`.
There is no `enable = false` attribute option to have the `encryption` block ignored.
See the bottom of the PR for an example & plan demonstrating the issue
(Also bumps the version in requirements to match the compatibility section)
---
**Example Usage:**
Here bucket `a` will have CMEK encryption and bucket `b` will have the default google managed encryption
```tf
module …
```
> Add encryption support

- README.md
- variables.tf
For best practices and for users who implement terragrunt [0]. Type constrains should be added [1]. Without specifying these constraints, applying a terragrunt plan/apply results in type errors [2], depending on the type constraints.
In terragrunt, "values are being passed in with environment variables and json, the type information is lost when crossing the boundary between Terragrunt and Terraform. You must specify the proper type constraint on the variable in Terraform in order for Terraform to process the inputs to the right type" [3].
tl;dr lists and maps currently do not work with terragrunt because type constraints are not explicitly set.
[0] https://github.com/gruntwork-io/terragrunt
[1] https://www.terraform.io/docs/configuration/variables.html#type-constraints
[2] Invalid value …
> Adding type constraints to variables

- README.md
- main.tf
- variables.tf
This PR adds support for the `cors` and `website` attribute blocks.
These are needed for managing buckets to be used as static sites.
https://www.terraform.io/docs/providers/google/r/storage_bucket.html#example-usage-creating-a-private-bucket-in-standard-storage-in-the-eu-region-bucket-configured-as-static-website-and-cors-configurations
I had to define the variables as `type = any` due to this issue: https://github.com/hashicorp/terraform/issues/19898
~I've also updated the `prefix` variable to have a default of an empty string. Which should be a nicer experience then having to explicitly set the attribute to an empty string as part of module inputs if you don't want a prefix and location info pre-pended to the bucket name.
Should make experiences like this a little cleaner: …
> add support for cors and  website blocks

- examples/multiple_buckets/README.md
- examples/multiple_buckets/main.tf
- examples/multiple_buckets/variables.tf
- test/fixtures/multiple_buckets/main.tf
For examples, we should try to only require project ID.
> chore: Simplify example setup

- README.md
- examples/multiple_buckets/main.tf
- main.tf
- modules/simple_bucket/main.tf
- test/integration/multiple_buckets/controls/gsutil.rb
- test/setup/main.tf
- test/setup/versions.tf
Google has deprecated the field `bucket_policy_only` in favor
of `uniform_bucket_level_access` and `bucket_policy_only`
will be removed in the next major release of the provider
Updated project-factory module in setup/main.tf
because v3 doesn't work with GCP provider v3.38.0
Resolves https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/79
> feat: Use uniform_bucket_level_access instead due to deprecation

- CHANGELOG.md
- modules/simple_bucket/versions.tf
> fix: Constrain minimum Google provider version to 3.38

- README.md
- main.tf
- outputs.tf
This prevents unnencesary recreation of resources when content/order of the
names list changes.
Addresses issue mentioned in: https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/73b7613cc062491305ebfabf8a8b1db0c53fc55b/foundations#things-to-be-aware-of
> use for_each instead of count to create resource

- Makefile
- README.md
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- main.tf
- test/setup/main.tf
- variables.tf
fixes #18
this adds changes from #22 which were not included in #86
also:
- improve existing variable descriptions and types
- update dev tools to: 0.12.0
- test/setup/main.tf: add skip_gcloud_download = true
- test/setup/main.tf: add missing iam.googleapis.com to activate_apis
> allow setting storage.admin and storage.hmacKeyAdmin roles

- README.md
- examples/multiple_buckets/README.md
- examples/multiple_buckets/variables.tf
- main.tf
- variables.tf
High. I have noticed that currently retention policy is supported only in `simple_bucket` module so I decided to jump in and add support for this feature also in the root module.
> Support retention policy

- README.md
- main.tf
- variables.tf
Google Cloud Storage buckets need globally unique names. Therefore, it's helpful to have a randomized component to names, especially for use in example code. The following code 
```
resource "random_id" "bucket" {
byte_length = 2
}
module "example_bucket" {
source     = "terraform-google-modules/cloud-storage/google"
version    = "~> 2.1"
project_id = var.project_id
location   = var.region
prefix = "myproject"
names  = ["data-${random_id.bucket.hex}"]
versioning = {
"data" : true
}
storage_class = "REGIONAL"
admins = [
module.sa_example.iam_email
]
depends_on = [
module.project_services
]
}
```
results in an error
```
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around …
```
> Add ability to append a randomized suffix to all bucket names

- modules/simple_bucket/README.md
- modules/simple_bucket/outputs.tf
Hi,
It would be nice to have the same outputs as the "multi cloud storage" module:
* Name of the storage account (to ensure dependency composition with main module or other modules)
* URL of the bucket
> feat: add name and url outputs on simple_bucket module

- README.md
- examples/multiple_buckets/main.tf
- main.tf
- test/integration/multiple_buckets/multiple_buckets_test.go
- variables.tf
Hi, in this PR I propose to have an option to set the argument `default_event_based_hold` with default value set to `false`. This will be useful for us who use this GCS Terraform module and have the requirement to enable object holds :smiley:
> Add option to enable default_event_based_hold argument

- .gitignore
From https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/173 without the tfvars change
> chore: update gitignore for codelab creds

- README.md
- examples/multiple_buckets/main.tf
- examples/simple_bucket/main.tf
- main.tf
- modules/simple_bucket/README.md
- modules/simple_bucket/main.tf
- modules/simple_bucket/variables.tf
- variables.tf
Add support for custom_placement_config which was added to provider in version [4.40.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4400-october-10-2022).
`custom_placement_config` is used for dual-region bucket configuration.
Docs for custom_placement_config: https://registry.terraform.io/providers/hashicorp/google/4.56.0/docs/resources/storage_bucket#custom_placement_config
> feat!: add support for custom_placement_config

- README.md
- main.tf
- modules/simple_bucket/README.md
- modules/simple_bucket/main.tf
- modules/simple_bucket/variables.tf
- modules/simple_bucket/versions.tf
- variables.tf
- versions.tf
Closes #301 
I'm new to contributing so I hope I did all that is needed
Tested this on our infra
> feat!: soft-delete configuration

- examples/multiple_buckets/main.tf
- main.tf
- test/integration/multiple_buckets/multiple_buckets_test.go
Currently, any `retention_policy` throws this error:
```
╷
│ Error: Invalid function argument
│
│   on .terraform\modules\my_buckets.gcs_bucket\main.tf line 114, in resource "google_storage_bucket" "buckets":
│  114:     for_each = lookup(var.retention_policy, each.value, {}) != {} ? [var.retention_policy[each.value]] : []
│     ├────────────────
│     │ while calling lookup(inputMap, key, default...)
│
│ Invalid value for "default" parameter: the default value must have the same type as the map elements.
╵
```
This fixes the default for the lookup, similar to https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/318. Given that this seems to be a recurring bug, it might be worth looking into 
https://github.com/terraform-google-modules/terraform-google-cloud-stor …
> fix: use null as default for lookup

- Makefile
- metadata.yaml
- modules/simple_bucket/main.tf
- modules/simple_bucket/metadata.yaml
This PR makes below changes,
1. Regenerate the metadata in current format. The current metadata is old and not in the current format.
2. Add new connection metadata for incoming connection from cloud-run module
> chore: Add connection metadata

- README.md
- metadata.yaml
- modules/simple_bucket/README.md
- modules/simple_bucket/metadata.yaml
- modules/simple_bucket/outputs.tf
- outputs.tf
Resource representation for GCS buckets should be `//storage.googleapis.com/<bucket-name>`. 
Also improved the logic of id generation.
> fix: Fix apphub uri and id representation

- docs/upgrading_to_v9.0.md
- modules/simple_bucket/README.md
- modules/simple_bucket/metadata.yaml
- modules/simple_bucket/outputs.tf
GCS buckets are not supported in AppHub yet!
> fix!: remove apphub_service_uri from output of simple_bucket

- metadata.yaml
- modules/simple_bucket/metadata.display.yaml
- modules/simple_bucket/metadata.yaml
- test/setup/iam.tf
This PR also downgrades roles required for running tests and applying examples.
> fix: update display metadata
